In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('multi_data.csv')
df

count  logged_in  srv_serror_rate  serror_rate  \
0      -0.717045  -0.809262        -0.631929    -0.637209   
1      -0.620982  -0.809262        -0.631929    -0.637209   
2       0.339648  -0.809262         1.605104     1.602664   
3      -0.690846   1.235694        -0.184522    -0.189235   
4      -0.472521   1.235694        -0.631929    -0.637209   
...          ...        ...              ...          ...   
125968  0.872361  -0.809262         1.605104     1.602664   
125969 -0.717045  -0.809262        -0.631929    -0.637209   
125970 -0.725778   1.235694        -0.631929    -0.637209   
125971  0.523041  -0.809262         1.605104     1.602664   
125972 -0.725778   1.235694        -0.631929    -0.637209   

        dst_host_serror_rate  dst_host_same_srv_rate  \
0                  -0.639532               -0.782367   
1                  -0.639532               -1.161030   
2                   1.608759               -0.938287   
3                  -0.572083                1.066401   
4                  -0.639532                1.066401   
...                      ...                     ...   
125968              1.608759               -0.938287   
125969             -0.639532                0.977304   
125970              0.979238               -0.893738   
125971              1.608759               -1.094207   
125972             -0.639532               -0.492801   

        dst_host_srv_serror_rate  dst_host_srv_count  same_srv_rate  \
0                      -0.624871           -0.818890       0.771283   
1                      -0.624871           -1.035688      -1.321428   
2                       1.618955           -0.809857      -1.389669   
3                      -0.602433            1.258754       0.771283   
4                      -0.624871            1.258754       0.771283   
...                          ...                 ...            ...   
125968                  1.618955           -0.818890      -1.184947   
125969                 -0.624871            1.159389       0.771283   
125970                 -0.624871           -0.773724       0.771283   
125971                  1.618955           -0.972455      -1.366922   
125972                 -0.624871           -0.349162       0.771283   

        protocol_type_icmp  ...  flag_S3  flag_SF  flag_SH  intrusion  Dos  \
0                        0  ...        0        1        0          4    0   
1                        0  ...        0        1        0          4    0   
2                        0  ...        0        0        0          0    1   
3                        0  ...        0        1        0          4    0   
4                        0  ...        0        1        0          4    0   
...                    ...  ...      ...      ...      ...        ...  ...   
125968                   0  ...        0        0        0          0    1   
125969                   0  ...        0        1        0          4    0   
125970                   0  ...        0        1        0          4    0   
125971                   0  ...        0        0        0          0    1   
125972                   0  ...        0        1        0          4    0   

        Probe  R2L  U2R  normal   label  
0           0    0    0       1  normal  
1           0    0    0       1  normal  
2           0    0    0       0     Dos  
3           0    0    0       1  normal  
4           0    0    0       1  normal  
...       ...  ...  ...     ...     ...  
125968      0    0    0       0     Dos  
125969      0    0    0       1  normal  
125970      0    0    0       1  normal  
125971      0    0    0       0     Dos  
125972      0    0    0       1  normal  

[125973 rows x 100 columns]

In [4]:
df.info

<bound method DataFrame.info of            count  logged_in  srv_serror_rate  serror_rate  \
0      -0.717045  -0.809262        -0.631929    -0.637209   
1      -0.620982  -0.809262        -0.631929    -0.637209   
2       0.339648  -0.809262         1.605104     1.602664   
3      -0.690846   1.235694        -0.184522    -0.189235   
4      -0.472521   1.235694        -0.631929    -0.637209   
...          ...        ...              ...          ...   
125968  0.872361  -0.809262         1.605104     1.602664   
125969 -0.717045  -0.809262        -0.631929    -0.637209   
125970 -0.725778   1.235694        -0.631929    -0.637209   
125971  0.523041  -0.809262         1.605104     1.602664   
125972 -0.725778   1.235694        -0.631929    -0.637209   

        dst_host_serror_rate  dst_host_same_srv_rate  \
0                  -0.639532               -0.782367   
1                  -0.639532               -1.161030   
2                   1.608759               -0.938287   
3          

In [5]:
x = df.drop(['label'], axis=1)
x

count  logged_in  srv_serror_rate  serror_rate  \
0      -0.717045  -0.809262        -0.631929    -0.637209   
1      -0.620982  -0.809262        -0.631929    -0.637209   
2       0.339648  -0.809262         1.605104     1.602664   
3      -0.690846   1.235694        -0.184522    -0.189235   
4      -0.472521   1.235694        -0.631929    -0.637209   
...          ...        ...              ...          ...   
125968  0.872361  -0.809262         1.605104     1.602664   
125969 -0.717045  -0.809262        -0.631929    -0.637209   
125970 -0.725778   1.235694        -0.631929    -0.637209   
125971  0.523041  -0.809262         1.605104     1.602664   
125972 -0.725778   1.235694        -0.631929    -0.637209   

        dst_host_serror_rate  dst_host_same_srv_rate  \
0                  -0.639532               -0.782367   
1                  -0.639532               -1.161030   
2                   1.608759               -0.938287   
3                  -0.572083                1.066401   
4                  -0.639532                1.066401   
...                      ...                     ...   
125968              1.608759               -0.938287   
125969             -0.639532                0.977304   
125970              0.979238               -0.893738   
125971              1.608759               -1.094207   
125972             -0.639532               -0.492801   

        dst_host_srv_serror_rate  dst_host_srv_count  same_srv_rate  \
0                      -0.624871           -0.818890       0.771283   
1                      -0.624871           -1.035688      -1.321428   
2                       1.618955           -0.809857      -1.389669   
3                      -0.602433            1.258754       0.771283   
4                      -0.624871            1.258754       0.771283   
...                          ...                 ...            ...   
125968                  1.618955           -0.818890      -1.184947   
125969                 -0.624871            1.159389       0.771283   
125970                 -0.624871           -0.773724       0.771283   
125971                  1.618955           -0.972455      -1.366922   
125972                 -0.624871           -0.349162       0.771283   

        protocol_type_icmp  ...  flag_S2  flag_S3  flag_SF  flag_SH  \
0                        0  ...        0        0        1        0   
1                        0  ...        0        0        1        0   
2                        0  ...        0        0        0        0   
3                        0  ...        0        0        1        0   
4                        0  ...        0        0        1        0   
...                    ...  ...      ...      ...      ...      ...   
125968                   0  ...        0        0        0        0   
125969                   0  ...        0        0        1        0   
125970                   0  ...        0        0        1        0   
125971                   0  ...        0        0        0        0   
125972                   0  ...        0        0        1        0   

        intrusion  Dos  Probe  R2L  U2R  normal  
0               4    0      0    0    0       1  
1               4    0      0    0    0       1  
2               0    1      0    0    0       0  
3               4    0      0    0    0       1  
4               4    0      0    0    0       1  
...           ...  ...    ...  ...  ...     ...  
125968          0    1      0    0    0       0  
125969          4    0      0    0    0       1  
125970          4    0      0    0    0       1  
125971          0    1      0    0    0       0  
125972          4    0      0    0    0       1  

[125973 rows x 99 columns]

In [6]:
y = df['label']
 
    
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

array([4, 4, 0, ..., 4, 0, 4])

In [7]:
print(le.classes_)

['Dos' 'Probe' 'R2L' 'U2R' 'normal']


In [8]:
# from sklearn.model_selection import train_test_split

# x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
# print(x_train, x_test, y_train, y_test)

In [9]:
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(n_estimators=10, learning_rate=10,random_state=0)

my_clf = abc.fit(x,y)

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [10]:
df1 = pd.read_excel('test_data.xlsx')
df1

count  logged_in  srv_serror_rate  serror_rate  dst_host_serror_rate  \
0    -0.699579   1.235694        -0.631929    -0.637209             -0.639532   
1     1.099419  -0.809262         1.605104     1.602664              1.608759   
2    -0.725778  -0.809262        -0.631929    -0.637209             -0.347254   
3    -0.717045   1.235694        -0.631929    -0.637209             -0.639532   
4     1.396341  -0.809262         1.605104     1.602664              1.608759   
...        ...        ...              ...          ...                   ...   
1000 -0.717045   1.235694        -0.631929    -0.637209             -0.639532   
1001 -0.009672   1.235694        -0.631929     1.580265             -0.639532   
1002 -0.708312   1.235694        -0.631929    -0.637209             -0.639532   
1003 -0.725778   1.235694        -0.631929    -0.637209             -0.639532   
1004 -0.725778   1.235694        -0.631929    -0.637209             -0.639532   

      dst_host_same_srv_rate  dst_host_srv_serror_rate  dst_host_srv_count  \
0                   1.066401                 -0.624871           -0.547893   
1                  -1.005110                  1.618955           -0.891156   
2                  -0.670995                  0.721425           -0.999555   
3                   1.066401                 -0.624871            1.258754   
4                  -0.982836                  1.618955           -0.864056   
...                      ...                       ...                 ...   
1000                1.066401                 -0.624871           -1.017621   
1001                1.066401                 -0.624871           -0.999555   
1002                1.066401                 -0.624871           -1.017621   
1003                1.066401                 -0.624871           -1.035688   
1004                0.331349                 -0.624871           -1.008588   

      same_srv_rate  protocol_type_icmp  ...  flag_S3  flag_SF  flag_SH  \
0          0.771283                   0  ...        0        1        0   
1         -1.321428                   0  ...        0        0        0   
2          0.771283                   0  ...        0        1        0   
3          0.771283                   0  ...        0        1        0   
4         -1.503403                   0  ...        0        0        0   
...             ...                 ...  ...      ...      ...      ...   
1000      -0.366060                   0  ...        0        1        0   
1001      -1.480656                   0  ...        0        1        0   
1002       0.771283                   0  ...        0        1        0   
1003       0.771283                   0  ...        0        1        0   
1004       0.771283                   0  ...        0        1        0   

      intrusion  Dos  Probe  R2L  U2R  normal   label  
0             0    1      0    0    0       0     Dos  
1             0    1      0    0    0       0     Dos  
2             4    0      0    0    0       1  normal  
3             4    0      0    0    0       1  normal  
4             0    1      0    0    0       0     Dos  
...         ...  ...    ...  ...  ...     ...     ...  
1000          3    0      0    0    1       0     U2R  
1001          3    0      0    0    1       0     U2R  
1002          3    0      0    0    1       0     U2R  
1003          3    0      0    0    1       0     U2R  
1004          3    0      0    0    1       0     U2R  

[1005 rows x 100 columns]

In [11]:
x_test = df1.drop(['label'], axis=1)
y_test = df1['label'] 
y_test

0          Dos
1          Dos
2       normal
3       normal
4          Dos
         ...  
1000       U2R
1001       U2R
1002       U2R
1003       U2R
1004       U2R
Name: label, Length: 1005, dtype: object

In [12]:
y_test = le.fit_transform(y_test)
y

array([4, 4, 0, ..., 4, 0, 4])

In [13]:
y_pred = my_clf.predict(x_test)
y_pred

array([0, 0, 4, ..., 3, 3, 3])

In [14]:
from sklearn.metrics import accuracy_score 

print('Accuracy: ',accuracy_score(y_test,y_pred))

Accuracy:  1.0


In [15]:
import joblib
joblib.dump(my_clf, 'adaboost_model.pkl')

['adaboost_model.pkl']

In [16]:
my_clf.predict([[-0.725778495,1.235694032,-0.631929033,-0.637209268,-0.639531905,-1.116481556,-0.6248708,-1.00858793,0.771283106,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0,1,0]])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


array([3])